apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: microservice-henry/product:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: product-configmap
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: product-configmap
                  key: DATABASE_PORT
            - name: DATABASE_DB
              valueFrom:
                configMapKeyRef:
                  name: product-configmap
                  key: DATABASE_DB
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: product-secrets
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-secrets
                  key: DATABASE_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: product-configmap
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: product-configmap
                  key: REDIS_PORT
